version: 2

sources:
  - name: raw
    database: project_champagne_retailer
    schema: sales
    tables: 
      - name: distributors
        description: List of distributors managing product imports in North America and distribution to retailers for Maison Étoile.
        columns:
          - name: distributor_id
            description: Unique identifier for a distributor.
            tests: 
              - not_null:
                  description: "A primary key can't be null." 
              - unique:
                  description: "A primary key has to contain only deduplicated values."  
          - name: distributor_name
            description: Name of the distributor.
          - name: country
            description: Country where the distributor is located in North America.

      - name: external_events
        description: List of major events that could have an influence on champagne sales in North America.
        columns: 
          - name: date 
            description: Date when the event took place.
          - name: country 
            description: Country where the event took place. 
          - name: region
            description: Region of the country where the event took place.
          - name: event_name 
            description: Name of the event that could have an influence on champagne sales. 
          - name: event_type
            description: Type of event.
            tests: 
              - accepted_values: 
                  values: ['holiday', 'festival', 'sport', 'weather']
          - name: impact_score
            description: Estimated impact of the event on champagne sales in North America.
            tests: 
              - not_null:
                  description: "The impact_score is the main information we need. It can't be null."  

      - name: market_top_sellers
        description: List of the most successful products sold by the direct competitors.
        columns:
          - name: period
            description: Year and month when the sales have been recorded for the most successful products sold by the direct competitors.
          - name: region 
            description: Country where the sales have been recorded for the most successful products sold by the direct competitors.
          - name: category
            description: Category of the product mentioned.
            tests:
              - not_null:
                  description: "The category is the part of the main information we need. It can't be null."  
          - name: top_brand
            description: Brand that generated the most sales for the category in the given period.
            tests:
              - not_null:
                  description: "The top brand is the part of the main information we need. It can't be null."  
          - name: est_units
            description: Number of individual sales generated by the top brand in the mentioned category, in the mentioned period.

      - name: products_catalog
        description: List of products sold in North America by our champagne brand, Maison Étoile.
        config:
          contract: 
            enforced: true
        constraints:
          - type: primary_key
            columns: [sku]
        columns:
          - name: sku
            data_type: VARCHAR
            description: Primary key of the table corresponding to the unique identifier of the product.
          - name: brand
            data_type: VARCHAR
            description: Name of the brand we help, Maison Étoile.
            tests: 
              - accepted_values: 
                  values: ['Maison Étoile']
          - name: cuvee
            data_type: VARCHAR
            description: Name of the cuvee, which is a kind of category.
          - name: bottle_size_ml
            data_type: NUMBER
            constraints:
              - type: not_null
            description: Volume in millimeters.
          - name: category 
            data_type: VARCHAR
            description: Category of the product sold by Maison Étoile.
            tests: 
              - accepted_values:
                  values:
                    ['Champagne']
          - name: upc
            data_type: NUMBER
            description: Universal product code.
            constraints:
              - type: not_null
              - type: unique
          - name: list_price_usd
            data_type: NUMBER
            description: Price of the product in US dollars.
            constraints: 
              - type: not_null 
          - name: list_price_cad 
            data_type: NUMBER
            description: Price of the product in Canadian dollars. 
            constraints: 
              - type: not_null 
          - name: launch_date
            data_type: DATE
            description: Date of launch of the product.
        
      - name: promotions 
        description: Contains all the details related to the promotions applied by distributors selling Maison Étoile brand over the past few months.
        columns:
          - name: promo_id
            description: Primary key of the table and unique identifier for a promotion.
            tests: 
              - not_null:
                  description: "A primary key can't be null." 
              - unique:  
                  description: "A primary key has to contain only deduplicated values." 
          - name: distributor_id 
            description: Distributor associated with the promotion. 
          - name: start_date 
            description: Date when the promotion started. 
          - name: end_date
            description: Date when the promotion ended, if it's not still ongoing.
          - name: discount_type 
            description: Type of discount that be fixed price or percentage of the base price. 
            tests: 
              - accepted_values:
                  values:
                    ['fixed', 'percent']
          - name: discount_value 
            description: Value of the discount, representing the money saved by the final consumer.
            tests: 
              - not_null: 
                  description: "The information is not useful if we don't the amount of the discount."
          - name: products 
            description: List of products on which the promotion applied. 
          - name: description
            description: Context of the promotion and description.

      - name: sales
        identifier: sales_distributors 
        description: Raw data containing all the sales of Maison Étoile in 2023 and 2024, in North America only.
        columns:
          - name: date 
            description: Date of the sale (payment completed by the customer). 
          - name: country
            description: Country where the customer made the sale. If physical sale, location of the store. If online sale, residency of the customer.
            tests:
              - not_null 
              - accepted_values:
                  values:
                    ['USA', 'Canada']
                    description: "We monitor only these two countries."
          - name: state_province
            description: State where the customer made the sale. If physical sale, location of the store. If online sale, residency of the customer.
          - name: distributor_id 
            description: ID of the distributor associated with the sale.
          - name: channel 
            description: Type of distribution for the channel through which the sale was made.
            tests:
              - accepted_values:
                  values:
                    ['On-Trade', 'Off-Trade', 'E-Commerce']
          - name: retailer_id
            description: ID of the retailer associated with the sale.
          - name: SKU
            description: "SKU of the product that was sold. Useful to identify the product sold."
            tests: 
            - not_null:
                description: "The SKU can't be null as it would prevent us from identifying the product sold."
          - name: product_name
            description: Name of the product that was sold.
          - name: bottle_size_ml
            description: Quantity of champagne in the bottle (in millimeters).
          - name: units
            description: Number of units purchased by the consumer within the identified sale. 
          - name: unit_price
            description: Price for one unit purchased.
          - name: currency
            description: Currency with which the transaction was realised. 
            tests:
              - not_null 
              - accepted_values:
                  values: 
                    ['USD', 'CAD']
          - name: discount_applied
            description: 0 if no discount was applied and 1 if a discount was applied during the sale.
            tests: 
              - accepted_values:
                  values: 
                    [0, 1]
                  
            
