version: 2

sources:
  - name: raw
    database: project_champagne_retailer
    schema: sales
    tables: 
      - name: distributors
        description: List of distributors managing products imports in North America and distribution to retailers for Maison Étoile.
        columns:
          - name: distributor_id
            description: Unique identifier for a distributor.
            tests: 
              - not_null
              - unique 
          - name: distributor_name
            description: Name of the distributor.
          - name: country
            description: Country where the distributor is located in North America.
      - name: external_events
        description: List of major events that could have an influence on champagne sales in North America.
        columns: 
          - name: date 
            description: Date when the event took place.
          - name: country 
            description: Country where the event took place. 
          - name: region
            description: Region of the country where the event took place.
          - name: event_name 
            description: Name of the event that could have an influence on champagne sales. 
          - name: event_type
            description: Type of event.
            tests: 
              - accepted_values: 
                  arguments:
                    values: ['holiday', 'festival', 'sport', 'weather']
          - name: impact_score
            description: Estimated impact of the event on sales of champagne in North America.
            tests: 
              - not_null
      - name: market_top_sellers
        description: List of the most successful products sold by the direct competitors.
        columns:
          - name: period
            description: Year and month when the sales have been recorded for the most successful products sold by the direct competitors.
          - name: region 
            description: Country where the sales have been recorded for the most successful products sold by the direct competitors.
          - name: category
            description: Category of the product mentioned.
            tests:
              - not_null
          - name: top_brand
            description: Brand that generated the most sales for the category on the period.
            tests:
              - not_null
          - name: est_units
            description: Number of inidvidual sales generated by the top brand in the mentioned category, on the mentioned period.
      - name: products_catalog
        description: List of products sold in North America by our champaign brand, Maison Étoile.
        columns:
          - name: sku
            description: Primary key of the table corresponding to the unique identifier of the product.
            tests:
              - not_null
              - unique 
          - name: brand
            description: Name of the brand we help, Maison Étoile.
            tests: 
              - accepted_values: 
                  arguments:
                    values: ['Maison Étoile']


