version: 2

sources:
  - name: raw
    database: project_champagne_retailer
    schema: sales
    tables: 
      - name: distributors
        description: List of distributors managing product imports in North America and distribution to retailers for Maison Étoile.
        columns:
          - name: distributor_id
            description: Unique identifier for a distributor.
            tests: 
              - not_null
              - unique 
          - name: distributor_name
            description: Name of the distributor.
          - name: country
            description: Country where the distributor is located in North America.

      - name: external_events
        description: List of major events that could have an influence on champagne sales in North America.
        columns: 
          - name: date 
            description: Date when the event took place.
          - name: country 
            description: Country where the event took place. 
          - name: region
            description: Region of the country where the event took place.
          - name: event_name 
            description: Name of the event that could have an influence on champagne sales. 
          - name: event_type
            description: Type of event.
            tests: 
              - accepted_values: 
                  values: ['holiday', 'festival', 'sport', 'weather']
          - name: impact_score
            description: Estimated impact of the event on champagne sales in North America.
            tests: 
              - not_null

      - name: market_top_sellers
        description: List of the most successful products sold by the direct competitors.
        columns:
          - name: period
            description: Year and month when the sales have been recorded for the most successful products sold by the direct competitors.
          - name: region 
            description: Country where the sales have been recorded for the most successful products sold by the direct competitors.
          - name: category
            description: Category of the product mentioned.
            tests:
              - not_null
          - name: top_brand
            description: Brand that generated the most sales for the category in the given period.
            tests:
              - not_null
          - name: est_units
            description: Number of individual sales generated by the top brand in the mentioned category, in the mentioned period.

      - name: products_catalog
        description: List of products sold in North America by our champagne brand, Maison Étoile.
        config:
          contract: 
            enforced: true
        columns:
          - name: sku
            data_type: VARCHAR
            description: Primary key of the table corresponding to the unique identifier of the product.
            tests:
              - not_null
              - unique 
          - name: brand
            data_type: VARCHAR
            description: Name of the brand we help, Maison Étoile.
            tests: 
              - accepted_values: 
                  values: ['Maison Étoile']
          - name: cuvee
            data_type: VARCHAR
            description: Name of the cuvee, which is a kind of category.
          - name: bottle_size_ml
            data_type: NUMBER
            description: Volume in millimeters.
            tests: 
              - not_null 
          - name: category 
            data_type: VARCHAR
            description: Category of the product sold by Maison Étoile.
            tests: 
              - accepted_values:
                  values:
                    ['Champagne']
          - name: upc
            data_type: NUMBER
            description: Universal product code.
            tests: 
              - not_null 
              - unique 
          - name: list_price_usd
            data_type: NUMBER
            description: Price of the product in US dollars.
            tests: 
              - not_null 
          - name: list_price_cad 
            data_type: NUMBER
            description: Price of the product in Canadian dollars. 
            tests: 
              - not_null 
          - name: launch_date
            data_type: DATE
            description: Date of launch of the product.
        
      - name: promotions 
        description: Contains all the details related to the promotions applied by distributors selling Maison Étoile brand over the past few months.
        columns:
          - name: promo_id
            description: Primary key of the table and unique identifier for a promotion.
            tests: 
              - not_null 
              - unique  
          - name: distributor_id 
            description: Distributor associated with the promotion. 
          - name: start_date 
            description: Date when the promotion started. 
            tests: 
              - not_null 
          - name: end_date
            description: Date when the promotion ended, if it's not still ongoing.
          - name: discount_type 
            description: Type of discount that be fixed price or percentage of the base price. 
            tests: 
              - accepted_values:
                  values:
                    ['fixed', 'percent']
          - name: discount_value 
            description: Value of the discount, representing the money saved by the final consumer.
            tests: 
              - not_null 
          - name: products 
            description: List of products on which the promotion applied. 
          - name: description
            description: Context of the promotion and description.
